name: Deploy to server

on: push

jobs:
  first_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Hola mundo
        run: echo "Hola mundo desde el primer job"

  second_jobs:
    runs-on: ubuntu-Lastest
    needs: first_jobs
    steps:
      - name: Hola mundo
        run: echo "Hola mundo desde el segundo job"
