name: Deploy to server

on:
  workflow_dispatch:

jobs:
  first_jobs:
    runs-on: alpine
    steps:
      - name: Hola mundo
        run: echo "Hola mundo desde el primer job"

  second_jobs:
    runs-on: ubuntu-latest
    needs: first_jobs
    if: ${{github.ref == 'refs/heads/main'}}
    steps:
      - name: List files
        run: ls -al
      - name: Checkout
        uses: actions/checkout@v4
      - name: workflow
        run: ls -al
        

