name: "Hola mundo"

on:
    push:
        branches:
        - main

jobs:
    deploy-codigofacilito:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              run: echo "Hola mundo desde GitHub Actions"
         
  

